default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

default: &mysql_adapter
  adapter: mysql2

test:
  <<: *default
  database: db/test.sqlite3


development:
   <<: *mysql_adapter
   database: rails_blog_dev
   username: rails
   password: test
   host: localhost

production:
   <<: *mysql_adapter
   database: database
   username: db_user
   password: db_pass
   host: localhost
